import type { Book } from '../types/book';

export const mockBooks: Book[] = [
  {
    id: '1',
    titulo: 'O Senhor dos Anéis: A Sociedade do Anel',
    autor: 'J.R.R. Tolkien',
    capa: 'https://images.unsplash.com/photo-1629992101753-56d196c8aabb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW50YXN5JTIwYm9vayUyMGNvdmVyJTIwZGVzaWdufGVufDF8fHx8MTc3NTI1NzgxMXww&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo terá uma longa jornada pela Terra-média e enfrentará grandes perigos.',
    categoria: 'lidos',
    minhaAvaliacao: 5,
    minhaResenha: 'Uma obra-prima da fantasia! A construção de mundo é incomparável.',
    dataAdicao: '2025-12-15',
  },
  {
    id: '2',
    titulo: '1984',
    autor: 'George Orwell',
    capa: 'https://images.unsplash.com/photo-1774328773475-35211ddddf63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rJTIwY292ZXIlMjBjbGFzc2ljJTIwbGl0ZXJhdHVyZXxlbnwxfHx8fDE3NzUxOTY4NTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Winston Smith vive em um regime totalitário onde o Grande Irmão controla tudo e todos. A liberdade é inexistente e a manipulação da verdade é constante. Uma distopia que nos faz refletir sobre poder, controle e liberdade.',
    categoria: 'lidos',
    minhaAvaliacao: 5,
    minhaResenha: 'Assustadoramente atual. Orwell foi visionário.',
    dataAdicao: '2026-01-10',
  },
  {
    id: '3',
    titulo: 'A Guerra dos Mundos',
    autor: 'H.G. Wells',
    capa: 'https://images.unsplash.com/photo-1772225027406-00bda64076b6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY2llbmNlJTIwZmljdGlvbiUyMGJvb2slMjBjb3ZlcnxlbnwxfHx8fDE3NzUxODQ2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Marcianos invadem a Terra com tecnologia superior, destruindo tudo em seu caminho. A humanidade luta pela sobrevivência neste clássico da ficção científica que inspirou gerações.',
    categoria: 'querendo-ler',
    dataAdicao: '2026-02-20',
  },
  {
    id: '4',
    titulo: 'O Código Da Vinci',
    autor: 'Dan Brown',
    capa: 'https://images.unsplash.com/photo-1760696473709-a7da66ee87a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxteXN0ZXJ5JTIwbm92ZWwlMjBib29rJTIwY292ZXJ8ZW58MXx8fHwxNzc1MjU3ODExfDA&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Robert Langdon é chamado ao Louvre para investigar um assassinato misterioso. Os símbolos deixados pelo morto o levarão a uma jornada de descobertas sobre segredos antigos e conspiração.',
    categoria: 'comprados',
    dataAdicao: '2026-03-05',
  },
  {
    id: '5',
    titulo: 'Orgulho e Preconceito',
    autor: 'Jane Austen',
    capa: 'https://images.unsplash.com/photo-1711185901354-73cb6b666c32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb21hbmNlJTIwbm92ZWwlMjBib29rJTIwY292ZXJ8ZW58MXx8fHwxNzc1MjM0MjMzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Elizabeth Bennet enfrenta pressões sociais e familiares enquanto navega pelos dilemas do amor e do casamento na Inglaterra do século XIX. Um romance atemporal sobre julgamentos precipitados.',
    categoria: 'biblioteca-particular',
    minhaAvaliacao: 4,
    minhaResenha: 'Romance clássico com personagens memoráveis e diálogos espirituosos.',
    dataAdicao: '2025-11-28',
  },
  {
    id: '6',
    titulo: 'O Alquimista',
    autor: 'Paulo Coelho',
    capa: 'https://images.unsplash.com/photo-1770235622326-fa1f885384be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBib29rJTIwZmljdGlvbiUyMGNvdmVyfGVufDF8fHx8MTc3NTI1NzgwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    sinopse: 'Santiago, um jovem pastor andaluz, parte em uma jornada em busca de um tesouro. Pelo caminho, aprende sobre sonhos, destino e a busca pela Lenda Pessoal.',
    categoria: 'interessantes',
    minhaAvaliacao: 3,
    dataAdicao: '2026-01-15',
  },
];
